export interface ProductoExtra {
  medidas: string[];
  presentacion: string;
  rendimiento: string;
  accesorios: string[];
}

export const PRODUCTOS_EXTRA: Record<string, ProductoExtra> = {
  'REM102-CEDRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color cedro / Caja de 8 un.",
        "1  Ángulo exterior metálico color cedro / Caja de 8 un.",
        "1  Ángulo de unión metálico color cedro / Caja de 8 un."],
  },
  'REM105-NEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color negro / Caja de 8 un.",
        "1  Ángulo exterior metálico color negro / Caja de 8 un.",
        "1  Ángulo de unión metálico color negro / Caja de 8 un."],
  },
  'REM108-NATURAL': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm",
        "Peso: 30 Kg"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de Inicio Metálico Color Madera / Caja de 8 un.",
        "1  Ángulo de Exterior Metálico Color Madera / Caja de 8 un.",
        "1  Ángulo de Unión Metálico Color Madera / Caja de 8 un."],
  },
  'REM108-ROBLE': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm",
        "Peso: 30 Kg"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: [],
  },
  'REM107-MADERA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm",
        "Peso: 30 Kg"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de Inicio Metálico Color Madera / Caja de 8 un.",
        "1  Ángulo de Exterior Metálico Color Madera / Caja de 8 un.",
        "1  Ángulo de Unión Metálico Color Madera / Caja de 8 un."],
  },
  'REM101-GRAFITO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color grafito / Caja de 8 un.",
        "1  Ángulo exterior metálico color grafito / Caja de 8 un.",
        "1  Ángulo de unión metálico color grafito / Caja de 8 un."],
  },
  'REM101-MADERA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color madera / Caja de 8 un.",
        "1  Ángulo exterior metálico color madera / Caja de 8 un.",
        "1  Ángulo de unión metálico color madera / Caja de 8 un."],
  },
  'REM102-CREMA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color crema / Caja de 8 un.",
        "1  Ángulo exterior metálico color crema / Caja de 8 un.",
        "1  Ángulo de unión metálico color crema / Caja de 8 un."],
  },
  'REM103-BLANCO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color blanco / Caja de 8 un.",
        "1  Ángulo exterior metálico color blanco / Caja de 8 un.",
        "1  Ángulo de unión metálico color blanco / Caja de 8 un."],
  },
  'REM103-NEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color negro / Caja de 8 un.",
        "1  Ángulo exterior metálico color negro / Caja de 8 un.",
        "1  Ángulo de unión metálico color negro / Caja de 8 un."],
  },
  'REM105-GRAFITO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color grafito / Caja de 8 un.",
        "1  Ángulo exterior metálico color grafito / Caja de 8 un.",
        "1  Ángulo de unión metálico color grafito / Caja de 8 un."],
  },
  'REG001-CREMA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm",
        "Peso: 32 Kg"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color negro / Caja de 8 un.",
        "1  Ángulo Exterior Texturizado Tipo Granito Crema AEG001 / Caja de 8 un."],
  },
  'REM101-NEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color negro / Caja de 8 un.",
        "1  Ángulo exterior metálico color negro / Caja de 8 un.",
        "1  Ángulo de unión metálico color negro / Caja de 8 un."],
  },
  'REM102-MADERA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color madera / Caja de 8 un.",
        "1  Ángulo exterior metálico color madera / Caja de 8 un.",
        "1  Ángulo de unión metálico color madera / Caja de 8 un."],
  },
  'REG001-NEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm",
        "Peso: 32 Kg"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color negro / Caja de 8 un.",
        "1  Ángulo Exterior Texturizado Tipo Granito Negro AEG001 / Caja de 8 un."],
  },
  'REG001-PIEDRA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 38.3 cm",
        "Grosor: 1.6 cm",
        "Peso: 32 Kg"],
    presentacion: "Caja de 8 un.",
    rendimiento: "8.80 m2 / Caja de 8 un.",
    accesorios: ["1  Ángulo de inicio metálico color negro / Caja de 8 un.",
        "1  Ángulo Exterior Texturizado Tipo Granito Piedra AEG001 / Caja de 8 un."],
  },
  'SPC101-GRAFITO': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: ["0.1  Guardapolvo SPC Grafito GPS101 / m2",
        "0.1  Cuarto Rodón SPC Grafito CPS101 / m2",
        "0.05  Nariz Grada SPC Grafito NPS101 / m2"],
  },
  'SPC101-GRISPIEDRA': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: ["0.1  Guardapolvo SPC Gris Piedra GPS101 / m2",
        "0.1  Cuarto Rodón SPC Gris Piedra CPS101 / m2",
        "0.05  Nariz Grada SPC Color Gris Piedra NPS101 / m2"],
  },
  'SPC101-CARBON': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: ["0.1  Cuarto Rodón SPC Carbón CPS101 / m2",
        "0.05  Nariz Grada SPC Carbón NPS101 / m2",
        "0.1  Guardapolvo SPC Carbón GPS101 / m2"],
  },
  'SPC101-NOGAL': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: ["0.1  Cuarto Rodón SPC Nogal CPS101 / m2",
        "0.05  Nariz Grada SPC Nogal NPS101 / m2",
        "0.1  Guardapolvo SPC Nogal GPS101 / m2"],
  },
  'SPC101-NATURAL': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: ["0.1  Cuarto Rodón SPC Natural CPS101 / m2",
        "0.05  Nariz Grada SPC Natural NPS101 / m2",
        "0.1  Guardapolvo SPC Natural GPS101 / m2"],
  },
  'SPC103-MARMOLPIEDRA': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: [],
  },
  'SPC103-MARMOLCREMA': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: [],
  },
  'SPC103-MARMOLCARBON': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: [],
  },
  'SPC101-CREMA': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: ["0.1  Guardapolvo SPC Crema GPS101 / m2",
        "0.1  Cuarto Rodón SPC Crema CPS101 / m2",
        "0.05  Nariz Grada SPC Crema NPS101 / m2"],
  },
  'SPC102-PARQUETNOGAL': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: [],
  },
  'SPC102-PARQUETGRAFITO': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: [],
  },
  'SPC102-PARQUETNATURAL': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: [],
  },
  'SPC103-MARMOLGRAFITO': {
    medidas: ["Largo: 122 cm",
        "Ancho: 18 cm",
        "Grosor: 0.55 cm"],
    presentacion: "Caja de 12 un.",
    rendimiento: "2.64 m2 / Caja de 12 un.",
    accesorios: [],
  },
  'PIM101-NOGAL': {
    medidas: ["Largo: 121 cm",
        "Ancho: 19 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Caja de 10 un.",
    rendimiento: "2.30 m2 / Caja de 10 un.",
    accesorios: [],
  },
  'PIM101-NATURAL': {
    medidas: ["Largo: 121 cm",
        "Ancho: 19 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Caja de 10 un.",
    rendimiento: "2.30 m2 / Caja de 10 un.",
    accesorios: [],
  },
  'PIM101-PIEDRA': {
    medidas: ["Largo: 121 cm",
        "Ancho: 19 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Caja de 10 un.",
    rendimiento: "2.30 m2 / Caja de 10 un.",
    accesorios: [],
  },
  'PIM101-GRAFITO': {
    medidas: ["Largo: 121 cm",
        "Ancho: 19 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Caja de 10 un.",
    rendimiento: "2.30 m2 / Caja de 10 un.",
    accesorios: [],
  },
  'PIM101-MADERA': {
    medidas: ["Largo: 121 cm",
        "Ancho: 19 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Caja de 10 un.",
    rendimiento: "2.30 m2 / Caja de 10 un.",
    accesorios: [],
  },
  'PIM101-CREMA': {
    medidas: ["Largo: 121 cm",
        "Ancho: 19 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Caja de 10 un.",
    rendimiento: "2.30 m2 / Caja de 10 un.",
    accesorios: [],
  },
  'PIM101-CEREZO': {
    medidas: ["Largo: 121 cm",
        "Ancho: 19 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Caja de 10 un.",
    rendimiento: "2.30 m2 / Caja de 10 un.",
    accesorios: [],
  },
  'PIM101-PARQUETROBLE': {
    medidas: ["Largo: 121 cm",
        "Ancho: 19 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Caja de 10 un.",
    rendimiento: "2.30 m2 / Caja de 10 un.",
    accesorios: [],
  },
  'PEW102-CAFEMADERA': {
    medidas: ["Largo: 220 cm",
        "Ancho: 14.2 cm",
        "Grosor: 2.2 cm"],
    presentacion: "Unidad",
    rendimiento: "0.32 m2 / Unidad",
    accesorios: ["2  Clip de inicio - término AEW101 / m2",
        "24  Clip de unión WPC negro AEW102 / m2",
        "0.5  Ángulo exterior coextruido WPC café chocolate ATW102 / m2"],
  },
  'PEW102-CAFECHOCOLATE': {
    medidas: ["Largo: 220 cm",
        "Ancho: 14.2 cm",
        "Grosor: 2.2 cm"],
    presentacion: "Unidad",
    rendimiento: "0.32 m2 / Unidad",
    accesorios: ["2  Clip de inicio - término AEW101 / m2",
        "24  Clip de unión WPC negro AEW102 / m2",
        "0.5  Ángulo exterior coextruido WPC café chocolate ATW102 / m2"],
  },
  'PEW102-GRISGRAFITO': {
    medidas: ["Largo: 220 cm",
        "Ancho: 14.2 cm",
        "Grosor: 2.2 cm"],
    presentacion: "Unidad",
    rendimiento: "0.32 m2 / Unidad",
    accesorios: ["2  Clip de inicio - término AEW101 / m2",
        "24  Clip de unión WPC negro AEW102 / m2",
        "0.5  Ángulo exterior coextruido WPC negro ATW102 / m2"],
  },
  'PEW102-NEGRO': {
    medidas: ["Largo: 220 cm",
        "Ancho: 14.2 cm",
        "Grosor: 2.2 cm"],
    presentacion: "Unidad",
    rendimiento: "0.32 m2 / Unidad",
    accesorios: ["2  Clip de inicio - término AEW101 / m2",
        "24  Clip de unión WPC negro AEW102 / m2",
        "0.5  Ángulo exterior coextruido WPC negro ATW102 / m2"],
  },
  'PEW101-CAFECHOCOLATE': {
    medidas: ["Largo: 220 cm",
        "Ancho: 14.2 cm",
        "Grosor: 2.2 cm",
        "Peso: 5.7 Kg"],
    presentacion: "Unidad",
    rendimiento: "0.32 m2 / Unidad",
    accesorios: ["2  Clip de inicio - término AEW101 / m2",
        "24  Clip de unión WPC negro AEW102 / m2",
        "0.5  Ángulo exterior coextruido WPC Café Chocolate ATW101 / m2"],
  },
  'PEW101-CAFEMADERA': {
    medidas: ["Largo: 220 cm",
        "Ancho: 14.2 cm",
        "Grosor: 2.2 cm",
        "Peso: 5.7 Kg"],
    presentacion: "Unidad",
    rendimiento: "0.32 m2 / Unidad",
    accesorios: ["2  Clip de inicio - término AEW101 / m2",
        "24  Clip de unión WPC negro AEW102 / m2",
        "0.5  Ángulo exterior coextruido WPC Café Madera ATW101 / m2"],
  },
  'PEW101-NEGRO': {
    medidas: ["Largo: 220 cm",
        "Ancho: 14.2 cm",
        "Grosor: 2.2 cm",
        "Peso: 5.7 Kg"],
    presentacion: "Unidad",
    rendimiento: "0.32 m2 / Unidad",
    accesorios: ["2  Clip de inicio - término AEW101 / m2",
        "24  Clip de unión WPC negro AEW102 / m2",
        "0.5  Ángulo exterior coextruido WPC Negro ATW101 / m2"],
  },
  'PEW101-GRISGRAFITO': {
    medidas: ["Largo: 220 cm",
        "Ancho: 14.2 cm",
        "Grosor: 2.2 cm",
        "Peso: 5.7 Kg"],
    presentacion: "Unidad",
    rendimiento: "0.32 m2 / Unidad",
    accesorios: ["2  Clip de inicio - término AEW101 / m2",
        "24  Clip de unión WPC negro AEW102 / m2",
        "0.5  Ángulo exterior coextruido WPC Gris Grafito ATW101 / m2"],
  },
  'PEW101-GRISPIEDRA': {
    medidas: ["Largo: 220 cm",
        "Ancho: 14.2 cm",
        "Grosor: 2.2 cm",
        "Peso: 5.7 Kg"],
    presentacion: "Unidad",
    rendimiento: "0.32 m2 / Unidad",
    accesorios: ["2  Clip de inicio - término AEW101 / m2",
        "24  Clip de unión WPC negro AEW102 / m2",
        "0.5  Ángulo exterior coextruido WPC Gris Piedra ATW101 / m2"],
  },
  'PIP002-GRISCENIZA': {
    medidas: ["Largo: 60 cm",
        "Ancho: 60 cm",
        "Grosor: 0.9 cm",
        "Peso: 29 Kg"],
    presentacion: "Caja de 4 un.",
    rendimiento: "1.44 m2 / Caja de 4 un.",
    accesorios: ["0.3  Saco de 25 Kg de adhesivo Bekron Doble Acción / m2",
        "0.15  Bolsa de 100 unidades de Niveladores 1.5 mm Torrews / m2",
        "0.05  Bolsa de 100 unidades de Cuñas Torrews / m2",
        "0.03  Bolsa de 200 unidades de espaciadores con tomador 2 mm Torrews / m2",
        "0.33  Bolsa de 1 Kg de Frague Color Gris / m2"],
  },
  'PIP002-CREMA': {
    medidas: ["Largo: 60 cm",
        "Ancho: 60 cm",
        "Grosor: 0.9 cm",
        "Peso: 29 Kg"],
    presentacion: "Caja de 4 un.",
    rendimiento: "1.44 m2 / Caja de 4 un.",
    accesorios: ["0.3  Saco de 25 Kg de adhesivo Bekron Doble Acción / m2",
        "0.15  Bolsa de 100 unidades de Niveladores 1.5 mm Torrews / m2",
        "0.05  Bolsa de 100 unidades de Cuñas Torrews / m2",
        "0.03  Bolsa de 200 unidades de espaciadores con tomador 2 mm Torrews / m2",
        "0.33  Bolsa de 1 Kg de Frague Color Almendra / m2"],
  },
  'PIP102-GRAFITO': {
    medidas: ["Largo: 60 cm",
        "Ancho: 60 cm",
        "Grosor: 0.9 cm"],
    presentacion: "Caja de 4 un.",
    rendimiento: "1.44 m2 / Caja de 4 un.",
    accesorios: [],
  },
  'PIP102-CARBON': {
    medidas: ["Largo: 60 cm",
        "Ancho: 60 cm",
        "Grosor: 0.9 cm"],
    presentacion: "Caja de 4 un.",
    rendimiento: "1.44 m2 / Caja de 4 un.",
    accesorios: [],
  },
  'PIP102-PIEDRA': {
    medidas: ["Largo: 60 cm",
        "Ancho: 60 cm",
        "Grosor: 0.9 cm"],
    presentacion: "Caja de 4 un.",
    rendimiento: "1.44 m2 / Caja de 4 un.",
    accesorios: [],
  },
  'PIP101-MADERA': {
    medidas: ["Largo: 120 cm",
        "Ancho: 20 cm",
        "Grosor: 1 cm"],
    presentacion: "Caja de 6 un.",
    rendimiento: "1.44 m2 / Caja de 6 un.",
    accesorios: [],
  },
  'PIP101-NOGAL': {
    medidas: ["Largo: 120 cm",
        "Ancho: 20 cm",
        "Grosor: 1 cm"],
    presentacion: "Caja de 6 un.",
    rendimiento: "1.44 m2 / Caja de 6 un.",
    accesorios: [],
  },
  'PIP101-ROBLE': {
    medidas: ["Largo: 120 cm",
        "Ancho: 20 cm",
        "Grosor: 1 cm"],
    presentacion: "Caja de 6 un.",
    rendimiento: "1.44 m2 / Caja de 6 un.",
    accesorios: [],
  },
  'PIP101-CAFEANTIQUE': {
    medidas: ["Largo: 120 cm",
        "Ancho: 20 cm",
        "Grosor: 1 cm"],
    presentacion: "Caja de 6 un.",
    rendimiento: "1.44 m2 / Caja de 6 un.",
    accesorios: [],
  },
  'REW202-MADERA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 21.9 cm",
        "Grosor: 2.6 cm"],
    presentacion: "Tabla",
    rendimiento: "1,72 Tabla / m2",
    accesorios: ["1  Clip de inicio - término AEW101 / m2",
        "0.2  Ángulo exterior coextruido WPC Café Madera ATW101 / m2"],
  },
  'REW201-MADERA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 14.6 cm",
        "Grosor: 2.1 cm"],
    presentacion: "Tabla",
    rendimiento: "2,65 Tabla / m2",
    accesorios: ["1  Clip de inicio - término AEW101 / m2",
        "0.2  Ángulo exterior coextruido WPC Café Madera ATW101 / m2"],
  },
  'REW202-NEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 21.9 cm",
        "Grosor: 2.6 cm"],
    presentacion: "Tabla",
    rendimiento: "1,72 Tabla / m2",
    accesorios: ["1  Clip de inicio - término AEW101 / m2",
        "0.2  Ángulo exterior coextruido WPC Café Chocolate ATW101 / m2"],
  },
  'REW202-CAFECHOCOLATE': {
    medidas: ["Largo: 290 cm",
        "Ancho: 21.9 cm",
        "Grosor: 2.6 cm"],
    presentacion: "Tabla",
    rendimiento: "1,72 Tabla / m2",
    accesorios: ["1  Clip de inicio - término AEW101 / m2",
        "0.2  Ángulo exterior coextruido WPC Café Chocolate ATW101 / m2"],
  },
  'REW201-CAFECHOCOLATE': {
    medidas: ["Largo: 290 cm",
        "Ancho: 14.6 cm",
        "Grosor: 2.1 cm"],
    presentacion: "Tabla",
    rendimiento: "2,65 Tabla / m2",
    accesorios: ["1  Clip de inicio - término AEW101 / m2",
        "0.2  Ángulo exterior coextruido WPC Café Chocolate ATW101 / m2"],
  },
  'REW201-NEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 14.6 cm",
        "Grosor: 2.1 cm"],
    presentacion: "Tabla",
    rendimiento: "2,65 Tabla / m2",
    accesorios: ["1  Clip de inicio - término AEW101 / m2",
        "0.2  Ángulo exterior coextruido WPC Negro ATW101 / m2"],
  },
  'REW103-GRAFITONEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 19.9 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Tabla",
    rendimiento: "1,73 Tabla / m2",
    accesorios: ["1  Clip de inicio - término AEW101 / m2"],
  },
  'REW103-ANTIQUENEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 19.9 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Tabla",
    rendimiento: "1,73 Tabla / m2",
    accesorios: ["1  Clip de inicio - término AEW101 / m2"],
  },
  'REW103-CHOCOLATENEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 19.9 cm",
        "Grosor: 1.6 cm"],
    presentacion: "Tabla",
    rendimiento: "1,73 Tabla / m2",
    accesorios: ["1  Clip de inicio - término AEW101 / m2"],
  },
  'RIW301-NATURAL': {
    medidas: ["Largo: 240 cm",
        "Ancho: 40 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Unidad",
    rendimiento: "0.96 m2 / Unidad",
    accesorios: ["5  Clip Unión AIW001 / Unidad"],
  },
  'RIW301-MADERA': {
    medidas: ["Largo: 240 cm",
        "Ancho: 40 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Unidad",
    rendimiento: "0.96 m2 / Unidad",
    accesorios: ["5  Clip Unión AIW001 / Unidad"],
  },
  'RIW201-CHOCOLATE': {
    medidas: ["Largo: 240 cm",
        "Ancho: 20 cm",
        "Grosor: 0.9 cm"],
    presentacion: "Unidad",
    rendimiento: "0.48 m2 / Unidad",
    accesorios: ["5  Clip Unión AIW001 / Unidad"],
  },
  'RIW201-MADERA': {
    medidas: ["Largo: 240 cm",
        "Ancho: 20 cm",
        "Grosor: 0.9 cm"],
    presentacion: "Unidad",
    rendimiento: "0.48 m2 / Unidad",
    accesorios: ["5  Clip Unión AIW001 / Unidad"],
  },
  'RIW201-CREMA': {
    medidas: ["Largo: 240 cm",
        "Ancho: 20 cm",
        "Grosor: 0.9 cm"],
    presentacion: "Tabla",
    rendimiento: "0.48 m2 / Tabla",
    accesorios: ["5  Clip Unión AIW001 / Tabla"],
  },
  'RIW301-BLANCO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 40 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Unidad",
    rendimiento: "0.96 m2 / Unidad",
    accesorios: ["5  Clip Unión AIW001 / Unidad"],
  },
  'RIW301-GRISPLATA': {
    medidas: ["Largo: 240 cm",
        "Ancho: 40 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Unidad",
    rendimiento: "0.96 m2 / Unidad",
    accesorios: ["5  Clip Unión AIW001 / Unidad"],
  },
  'RIW101-CEDRONEGRO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 15.5 cm",
        "Grosor: 1.7 cm"],
    presentacion: "Tabla",
    rendimiento: "0.37 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW301-GRISGRAFITO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 40 cm",
        "Grosor: 0.8 cm"],
    presentacion: "Unidad",
    rendimiento: "0.96 m2 / Unidad",
    accesorios: ["5  Clip Unión AIW001 / Unidad"],
  },
  'RIW101-CHOCOLATENEGRO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 15.5 cm",
        "Grosor: 1.7 cm"],
    presentacion: "Tabla",
    rendimiento: "0.37 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW101-CREMANEGRO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 15.5 cm",
        "Grosor: 1.7 cm"],
    presentacion: "Tabla",
    rendimiento: "0.37 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW101-MADERANEGRO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 15.5 cm",
        "Grosor: 1.7 cm"],
    presentacion: "Tabla",
    rendimiento: "0.37 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW102-NEGRO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 19.5 cm",
        "Grosor: 2.8 cm"],
    presentacion: "Tabla",
    rendimiento: "0.47 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW102-CEDRO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 19.5 cm",
        "Grosor: 2.8 cm"],
    presentacion: "Tabla",
    rendimiento: "0.47 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW103-CEDRO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 15.5 cm",
        "Grosor: 1.7 cm"],
    presentacion: "Tabla",
    rendimiento: "0.37 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW103-MADERA': {
    medidas: ["Largo: 240 cm",
        "Ancho: 15.5 cm",
        "Grosor: 1.7 cm"],
    presentacion: "Tabla",
    rendimiento: "0.37 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW103-CHOCOLATE': {
    medidas: ["Largo: 240 cm",
        "Ancho: 15.5 cm",
        "Grosor: 1.7 cm"],
    presentacion: "Tabla",
    rendimiento: "0.37 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW103-CREMA': {
    medidas: ["Largo: 240 cm",
        "Ancho: 15.5 cm",
        "Grosor: 1.7 cm"],
    presentacion: "Tabla",
    rendimiento: "0.37 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'RIW103-NEGRO': {
    medidas: ["Largo: 240 cm",
        "Ancho: 15.5 cm",
        "Grosor: 1.7 cm"],
    presentacion: "Tabla",
    rendimiento: "0.37 m2 / Tabla",
    accesorios: ["10  Clip Unión AIW001 / m2"],
  },
  'CVW201-CAFECHOCOLATE': {
    medidas: ["Largo: 290 cm",
        "Ancho: 7.2 cm",
        "Grosor: 1.1 cm"],
    presentacion: "Tabla",
    rendimiento: "4,93 Tabla / m2",
    accesorios: [],
  },
  'CVW201-NEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 7.2 cm",
        "Grosor: 1.1 cm"],
    presentacion: "Tabla",
    rendimiento: "4,93 Tabla / m2",
    accesorios: [],
  },
  'CVW101-CAFEMADERA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 7 cm",
        "Grosor: 1 cm"],
    presentacion: "Tabla",
    rendimiento: "0.20 m2 / Tabla",
    accesorios: [],
  },
  'CVW101-GRISGRAFITO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 7 cm",
        "Grosor: 1 cm"],
    presentacion: "Tabla",
    rendimiento: "0.20 m2 / Tabla",
    accesorios: [],
  },
  'CVW101-GRISPIEDRA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 7 cm",
        "Grosor: 1 cm"],
    presentacion: "Tabla",
    rendimiento: "0.20 m2 / Tabla",
    accesorios: [],
  },
  'CVW101-CAFEANTIQUE': {
    medidas: ["Largo: 290 cm",
        "Ancho: 7 cm",
        "Grosor: 1 cm"],
    presentacion: "Tabla",
    rendimiento: "0.20 m2 / Tabla",
    accesorios: [],
  },
  'CVW101-CAFECHOCOLATE': {
    medidas: ["Largo: 290 cm",
        "Ancho: 7 cm",
        "Grosor: 1 cm"],
    presentacion: "Tabla",
    rendimiento: "0.20 m2 / Tabla",
    accesorios: [],
  },
  'CVW101-NEGRO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 7 cm",
        "Grosor: 1 cm"],
    presentacion: "Tabla",
    rendimiento: "0.20 m2 / Tabla",
    accesorios: [],
  },
  'REP101-BLANCO': {
    medidas: ["Largo: 290 cm",
        "Ancho: 20 cm",
        "Grosor: 0.1 cm"],
    presentacion: "Unidad",
    rendimiento: "1,72 Unidad / m2",
    accesorios: [],
  },
  'REP101-BEIGE': {
    medidas: ["Largo: 290 cm",
        "Ancho: 20 cm",
        "Grosor: 0.1 cm"],
    presentacion: "Unidad",
    rendimiento: "1,72 Unidad / m2",
    accesorios: [],
  },
  'REP101-GRISPIEDRA': {
    medidas: ["Largo: 290 cm",
        "Ancho: 20 cm",
        "Grosor: 0.1 cm"],
    presentacion: "Unidad",
    rendimiento: "1,72 Unidad / m2",
    accesorios: [],
  },
  'REP101-CAFE': {
    medidas: ["Largo: 290 cm",
        "Ancho: 20 cm",
        "Grosor: 0.1 cm"],
    presentacion: "Unidad",
    rendimiento: "1,72 Unidad / m2",
    accesorios: [],
  },
  'RPU101-COBRE': {
    medidas: ["Largo: 150 cm",
        "Ancho: 75 cm",
        "Grosor: 6 cm"],
    presentacion: "Unidad",
    rendimiento: "0,89 Unidad / m2",
    accesorios: [],
  },
  'RPU101-GRAFITO': {
    medidas: ["Largo: 150 cm",
        "Ancho: 75 cm",
        "Grosor: 6 cm"],
    presentacion: "Unidad",
    rendimiento: "0,89 Unidad / m2",
    accesorios: [],
  },
  'RPU101-CAFEMADERA': {
    medidas: ["Largo: 150 cm",
        "Ancho: 75 cm",
        "Grosor: 6 cm"],
    presentacion: "Unidad",
    rendimiento: "0,89 Unidad / m2",
    accesorios: [],
  },
  'RPU101-PIEDRAVOLCANICA': {
    medidas: ["Largo: 150 cm",
        "Ancho: 75 cm",
        "Grosor: 6 cm"],
    presentacion: "Unidad",
    rendimiento: "0,89 Unidad / m2",
    accesorios: [],
  },
  'RPU101-PIEDRA': {
    medidas: ["Largo: 150 cm",
        "Ancho: 75 cm",
        "Grosor: 6 cm"],
    presentacion: "Unidad",
    rendimiento: "0,89 Unidad / m2",
    accesorios: [],
  },
  'RPU101-FACHALETA': {
    medidas: ["Largo: 120 cm",
        "Ancho: 60 cm",
        "Grosor: 2 cm"],
    presentacion: "Unidad",
    rendimiento: "1,40 Unidad / m2",
    accesorios: [],
  },
  'APU102-CAFE': {
    medidas: ["Largo: 290 cm",
        "Ancho: 20 cm",
        "Grosor: 15 cm"],
    presentacion: "Unidad",
    rendimiento: "0.58 m2 / Unidad",
    accesorios: [],
  },
  'APU102-NOGAL': {
    medidas: ["Largo: 290 cm",
        "Ancho: 20 cm",
        "Grosor: 15 cm"],
    presentacion: "Unidad",
    rendimiento: "0.58 m2 / Unidad",
    accesorios: [],
  },
  'CEW01-180-CAFE': {
    medidas: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
    presentacion: "Kit con accesorios",
    rendimiento: "3.39 m2 / Kit con accesorios",
    accesorios: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
  },
  'CEW01-180-NEGRO': {
    medidas: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
    presentacion: "Kit con accesorios",
    rendimiento: "3.39 m2 / Kit con accesorios",
    accesorios: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
  },
  'CEW02-180-CAFE': {
    medidas: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
    presentacion: "Kit con accesorios",
    rendimiento: "3.39 m2 / Kit con accesorios",
    accesorios: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
  },
  'CEW02-180-NEGRO': {
    medidas: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
    presentacion: "Kit con accesorios",
    rendimiento: "3.39 m2 / Kit con accesorios",
    accesorios: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
  },
  'CEW03-180-CAFE': {
    medidas: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
    presentacion: "Kit con accesorios",
    rendimiento: "3.39 m2 / Kit con accesorios",
    accesorios: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
  },
  'CEW03-180-NEGRO': {
    medidas: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
    presentacion: "Kit con accesorios",
    rendimiento: "3.39 m2 / Kit con accesorios",
    accesorios: ["Largo: 186 cm",
        "Ancho: 182 cm",
        "Grosor: 2 cm"],
  },
};

export function getProductoExtra(sku: string): ProductoExtra | undefined {
  return PRODUCTOS_EXTRA[sku];
}